# This is a basic workflow to help you get started with Actions

name: GoogleCloudStorage


on:

  push:
    branches:
    - master
  
  workflow_dispatch:

env:
  CS_BUCKET: ${{ secrets.GCS_BUCKET }}

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCS_SA_KEY }}
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup - gcloud / gsutil
      uses: 'google-github-actions/setup-gcloud@v0'
     
    - name: Deploy
      run: |-
        gsutil -m rsync -R output gs://$GCS_BUCKET
