# This is a basic workflow to help you get started with Actions

name: GoogleCloudStorage


on:

  push:
    branches:
    - master
  
  workflow_dispatch:

env:
  CS_BUCKET: ${{ secrets.GCS_BUCKET }}

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup - gcloud / gsutil
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        project_id: ${{ secrets.GCS_PROJECT }}
        export_default_credentials: true

    - name: Deploy
      run: |-
        gsutil -m rsync -R output gs://$GCS_BUCKET
