# This is a basic workflow to help you get started with Actions

name: GoogleCloudStorage


on:

  push:
    branches:
    - master
  
  workflow_dispatch:

env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}

jobs:
 infrastructure:
    runs-on: ubuntu-latest
    name: Setup, Build, and Deploy
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCS_SA_KEY2 }}'

    - name: Setup - gcloud / gsutil
      uses: 'google-github-actions/setup-gcloud@v0'
     
    - name: Deploy
      run: |-
        gsutil -m rsync -R docs gs://$GCS_BUCKET/
